// EXEMPLE - Fichier de données avec images locales
// Ce fichier montre comment utiliser les images locales après remplacement
// Copiez ce contenu dans src/lib/data.ts après avoir remplacé vos images

import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Viande fumée de porc',
    slug: 'viande-fumee-de-porc',
    category: 'Viandes',
    price: 15.99,
    description: 'Délicieuse viande de porc fumée, préparée selon des méthodes traditionnelles pour une saveur authentique.',
    image: '/assets/images/products/viandes/viande_fumee_porc.jpg',
    dataAiHint: 'smoked meat',
  },
  {
    id: 2,
    name: 'Lardons fumés',
    slug: 'lardons-fumes',
    category: 'Viandes',
    price: 8.49,
    description: 'Lardons fumés de qualité supérieure, parfaits pour rehausser vos plats et salades.',
    image: '/assets/images/products/viandes/lardons_fumes.jpg',
    dataAiHint: 'smoked bacon',
  },
  {
    id: 3,
    name: 'Saucisses',
    slug: 'saucisses',
    category: 'Viandes',
    price: 12.00,
    description: 'Saucisses artisanales, juteuses et savoureuses, idéales pour le barbecue ou la poêle.',
    image: '/assets/images/products/viandes/saucisses.jpg',
    dataAiHint: 'sausages grill',
  },
  {
    id: 4,
    name: 'Jus d\'ananas',
    slug: 'jus-ananas',
    category: 'Boissons naturelles',
    price: 4.50,
    description: 'Jus d\'ananas 100% pur et naturel, sans sucre ajouté, pour une dose de fraîcheur tropicale.',
    image: '/assets/images/products/boissons_naturelles/jus_ananas.jpg',
    dataAiHint: 'pineapple juice',
  },
  {
    id: 5,
    name: 'Jus d\'orange',
    slug: 'jus-orange',
    category: 'Boissons naturelles',
    price: 4.00,
    description: 'Jus d\'orange fraîchement pressé, riche en vitamine C et au goût intense.',
    image: '/assets/images/products/boissons_naturelles/jus_orange.jpg',
    dataAiHint: 'orange juice',
  },
  {
    id: 6,
    name: 'Jus de prune',
    slug: 'jus-prune',
    category: 'Boissons naturelles',
    price: 5.00,
    description: 'Jus de prune onctueux et riche en fibres, pour un bien-être naturel.',
    image: '/assets/images/products/boissons_naturelles/jus_prune.jpg',
    dataAiHint: 'plum juice',
  },
  {
    id: 7,
    name: 'Jus de passiflore',
    slug: 'jus-passiflore',
    category: 'Boissons naturelles',
    price: 5.50,
    description: 'Jus de fruit de la passion exotique et rafraîchissant, au parfum envoûtant.',
    image: '/assets/images/products/boissons_naturelles/jus_passiflore.jpg',
    dataAiHint: 'passionfruit juice',
  },
  {
    id: 8,
    name: 'Jus de mangue',
    slug: 'jus-mangue',
    category: 'Boissons naturelles',
    price: 5.20,
    description: 'Nectar de mangue doux et velouté, un vrai régal pour les papilles.',
    image: '/assets/images/products/boissons_naturelles/jus_mangue.jpg',
    dataAiHint: 'mango juice',
  },
  {
    id: 9,
    name: 'Jus de gingembre',
    slug: 'jus-gingembre',
    category: 'Boissons naturelles',
    price: 4.80,
    description: 'Jus de gingembre épicé et vivifiant, parfait pour un coup de boost.',
    image: '/assets/images/products/boissons_naturelles/jus_gingembre.jpg',
    dataAiHint: 'ginger juice',
  },
  {
    id: 10,
    name: 'Jus de citron',
    slug: 'jus-citron',
    category: 'Boissons naturelles',
    price: 3.50,
    description: 'Jus de citron pur, idéal pour vos assaisonnements, boissons ou cures détox.',
    image: '/assets/images/products/boissons_naturelles/jus_citron.jpg',
    dataAiHint: 'lemon juice',
  },
  {
    id: 11,
    name: 'Gaz',
    slug: 'gaz',
    category: 'Autres produits',
    price: 25.00,
    description: 'Recharge de bouteille de gaz pour votre cuisine. Service rapide et fiable.',
    image: '/assets/images/products/autres_produits/gaz.jpg',
    dataAiHint: 'gas canister',
  },
  {
    id: 12,
    name: 'Shikwange',
    slug: 'shikwange',
    category: 'Autres produits',
    price: 7.00,
    description: 'Le traditionnel shikwange, un accompagnement incontournable de la cuisine congolaise.',
    image: '/assets/images/products/autres_produits/shikwange.jpg',
    dataAiHint: 'african food',
  },
  {
    id: 13,
    name: 'Vin Rouge - Celar',
    slug: 'vin-celar',
    category: 'Vins rouges',
    price: 18.00,
    description: 'Un vin rouge équilibré avec des notes de fruits rouges et une finale douce.',
    image: '/assets/images/products/vins_rouges/vin_celar.jpg',
    dataAiHint: 'red wine',
  },
  {
    id: 14,
    name: 'Vin Rouge - Drosdy',
    slug: 'vin-drosdy',
    category: 'Vins rouges',
    price: 22.50,
    description: 'Vin rouge Drosdy, riche et corsé, parfait pour accompagner vos viandes.',
    image: '/assets/images/products/vins_rouges/vin_drosdy.jpg',
    dataAiHint: 'wine bottle',
  },
  {
    id: 15,
    name: 'Vin Rouge - Baron',
    slug: 'vin-baron',
    category: 'Vins rouges',
    price: 15.00,
    description: 'Vin rouge Baron, élégant et fruité, idéal pour les moments de détente.',
    image: '/assets/images/products/vins_rouges/vin_baron.jpg',
    dataAiHint: 'wine bottle',
  },
];
